language: generic
deploy:
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: aws-website-beta.pallet.io
    cache_control: "no-cache"
    on:
      branch: master
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: aws-website-pallet.io
    on:
      tags: true
